CREATE TABLE "SYSTEM"."TIA_USERS" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
	 )