CREATE or REPlACE TABLE "SYSTEM"."FM_USERS" 
(	
	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "FM_USERS_PK" PRIMARY KEY ("ID")
);

commit;